name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  cpp-build:
    name: C++
    runs-on: ubuntu-latest
    # Keep in mind that ubuntu-latest is a rolling release, and that we heavily
    # rely on its builtin CMake, Ninja, clang-tidy, etc. in order for this CI
    # build to work. To learn more about the runner images:
    # https://github.com/actions/runner-images

    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake --preset ci
      - name: Run build
        run: cmake --build --preset ci
      - name: Run tests
        run: ctest --test-dir build --output-on-failure
