name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  cpp-build:
    name: C++
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug
      - name: Build
        run: cmake --build build --config Debug
      - name: Run Tests
        run: ctest --test-dir build --output-on-failure
